site_name: UnB - QuantumVR

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: red
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tabs.sticky

repo_url: https://github.com/bolzanMGB/2026.2-UnB-PIBIC-QuantumVR

extra_css:
  - assets/stylesheets/global.css
  
markdown_extensions:
  - admonition
  - tables
  - pymdownx.betterem
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Fundamentos:
    - Evolução Histórica dos Modelos Atômicos: 01-fundamentos/1.1-historico-modelos.md 
    - Modelo Atômico Atual: 01-fundamentos/1.2-modelo-atual.md 
  - Revisão de Literatura: 
    - Artigos : 02-analise-artigos/2.1-artigos.md
    - Immersive Quantum : 02-analise-artigos/2.2-immersive-quantum.md